<div class="change_Password">
        <form action="<?= $requestUrl ?>/infos/newmdp" method="POST">
            <div>
                <?php if(isset($error)){ ?>
                    <p class='red'> <?= $error ?> </p>
                <?php } ?>	
                <label for='oldPassword'> Ancien mot de passe :</label>
                <input type="password" name="oldPassword" id="oldPassword">
                <label for="newPassword"> Nouveau mot de passe :</label>
                <input type="password" name="newPassword" id="newPassword">
                <label for="confirmPassword"> Confirmer mot de passe :</label>
                <input type="password" name="confirmPassword" id="confirmPassword">    
            </div>			
            <div>
                <input type="submit" value="Enregistrer">
            </div>
        </form>
    </div>
