<div class="change_Password">
        <form action="<?= $requestUrl ?>/infos/newmdp" method="POST">
            <div>
                <?php if(isset($error)){ ?>
                    <p class='red'> <?= $error ?> </p>
                <?php } ?>	
                <label for='oldPassword'> Ancien mot de passe :
                    <input type="password" name="oldPassword">
                </label>
                <label for="newPassword"> Nouveau mot de passe :
                    <input type="password" name="newPassword">
                </label>
                <label for="confirmPassword"> Confirmer mot de passe :
                    <input type="password" name="confirmPassword">
                </label>						
            </div>			
            <div>
                <input type="submit" value="Enregistrer">
            </div>
        </form>
    </div>