<div class="change_Infos">
        <form action="<?= $requestUrl ?>/infos/newinfos" method="POST">
            <?php if(isset($error)){ ?>
            <p class="red"> <?= $error ?> </p>
            <?php } ?>
            <div>	
                <label for="firstName"> Nom :</label>
                <input type="text" name="firstName" id="firstName" value="<?= $_SESSION['firstName'] ?>">
                <label for="lastName"> Prénom :</label>
                <input type="text" name="lastName" id="lastName" value="<?= $_SESSION['lastName'] ?>">
                <label for="email"> Email :</label>
                <input type="email" name="email" id="email" value="<?= $_SESSION['email'] ?>">
            </div>			
            <div>
                <input type="submit" value="Enregistrer">
            </div>
        </form>
    </div>
