<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Best of citations</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    
    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/Best-Style.css">
    <!-- Librairie jQuery -->
    <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>
<header>
    <nav>
        <div>  
            <a class='logo' href="<?= $requestUrl ?>/">
                <img src="<?= $wwwUrl ?>/images/logo.png" alt="logo">
            </a>
        </div>
        <div class="layout_a nav_header">    
            <?php if(empty($_SESSION)){ ?>
                <a href="<?= $requestUrl ?>/register">S'inscrire</a>
                <a href="<?= $requestUrl ?>/login">Connexion</a>
            <?php }else{ ?>
                <a href="<?= $requestUrl ?>/game">Mini jeu</a>    
                <a href="<?= $requestUrl ?>/favorite">Mes favories</a>
                <a href="<?= $requestUrl ?>/infos"><?= $_SESSION['firstName'] ?> <?= $_SESSION['lastName'] ?></a>
                <a href="<?= $requestUrl ?>/logout">Déconnexion</a>
            <?php } ?>
        </div>
    </nav>
</header>


<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>
</main>

<!-- Pied de page commun -->
<footer>
    <div class="layout_a">
        <a href="https://www.facebook.com/">Facebook</a>
        <a href="https://www.instagram.com/?hl=fr">Instagram</a>
        <a href="https://www.linkedin.com/in/amar-jaha-11b2301a1/">Linkedin</a>
        <a href="https://twitter.com/login?lang=fr">Twitter</a>        
    </div>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>